server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false

unleash:
  appName: demo
  endpoint: http://localhost:4242/api/
  fetchTogglesInterval: 10
  sendMetricsInterval: 10