version: '3'
services:
  unleash-server:
    image: unleashorg/unleash-server
    ports:
      - 4242:4242
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/unleash
      HTTP_PORT: 4242
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "${POSTGRES_IMAGE_VERSION}"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unleash
